pub struct Awos {
    eff_date: i32,
    asos_awos_id: i32,
    asos_awos_type: i32,
    state_code: i32,
    city: String,
    country_code: i32,
    commissioned_date: i32,
    navaid_flag: i32,
    lat_deg: i32,
    lat_min: i32,
    lat_sec: i32,
    lat_hemis: i32,
    lat_decimal: i32,
    long_deg: i32,
    long_min: i32,
    long_sec: i32,
    long_hemis: i32,
    long_decimal: i32,
    elev: i32,
    survey_method_code: i32,
    phone_no: i32,
    second_phone_no: i32,
    site_no: i32,
    site_type_code: i32,
    remark: i32,
}
