name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dev dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-dev
        
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cargo-geiger and clippy
        run: |
          rustup component add clippy-preview

      - name: Run clippy
        run: cargo clippy -- -D warnings
