name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cargo-geiger and clippy
        run: |
          rustup component add clippy-preview
          cargo install cargo-geiger

      - name: Check for unsafe code in Scraper
        run: cargo geiger --manifest-path=scraper/Cargo.toml --all-features --deny-unsafe

      - name: Run clippy
        run: cargo clippy -- -D warnings
